### ISSUE TITLE
Email nebyl doručen

### ISSUE THREAD

**Issue by MCvojtik** [mare-on/Chat-Bot#11]
Zaregistroval jsem se do Programu, avšak žádný potvrzovací email mi dosud nepřišel.

**Comment by mare-on** [comment]
Stává se, že mail padá do složky se Spamem, nezapadlo to tam?

**Comment by MCvojtik** [comment]
Nope, zprávu na gmailu nikde nemám.

**Comment by mare-on** [comment]
Zkus prosím provést registraci ještě jednou, jestli to od té doby nebylo v některém commitu opraveno.
